[package]
name = "bao-wasm"
version = "0.1.0"
authors = ["Richard Vade <ivmidable@gmail.com>"]
description = "wasm bindings for bao"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"
bao = "0.12.1"